apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elasticsearch.fullname" . | quote }}
  labels:
    app: {{ template "elasticsearch.name" . | quote }}
    chart: {{ template "elasticsearch.chart" . | quote }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
  elasticsearch_custom.yml: |-

    cloud:
      kubernetes:
        service: {{ template "master.fullname" . | quote }}
        namespace: {{ .Release.Namespace | quote }}

    discovery:
      zen:
        hosts_provider: kubernetes
        minimum_master_nodes: 2

    plugin:
      mandatory: discovery-kubernetes

{{- if .Values.config }}
{{ toYaml .Values.config | indent 4 }}
{{- end }}
