{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "metrics.fullname" . }}"
  labels:
    app: "{{ template "name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{ toYaml .Values.metrics.annotations | indent 4 }}
spec:
  ports:
  - name: metrics
    port: 9108
    targetPort: metrics
  selector:
    app: "{{ template "name" . }}"
    release: "{{ .Release.Name }}"
    role: "metrics"
{{- end }}
