{{- if .Values.metrics.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "metrics.fullname" . | quote }}
  labels:
    app: {{ template "elasticsearch.name" . | quote }}
    chart: {{ template "elasticsearch.chart" . | quote }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    role: "metrics"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "elasticsearch.name" . | quote }}
        release: {{ .Release.Name | quote }}
        role: "metrics"
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      containers:
      - name: {{ template "metrics.fullname" . }}
        image:  {{ template "metrics.image" . | quote }}
        imagePullPolicy: {{ .Values.metrics.image.pullPolicy | quote }}
        args: [ "-es.uri=http://{{ template "coordinating.fullname" . }}:{{ .Values.coordinating.service.port }}", "-es.all=true" ]
        ports:
        - name: metrics
          containerPort: 9108
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
{{ toYaml .Values.metrics.resources | indent 10 }}
{{- end }}
