{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "metrics.fullname" . | quote }}
  labels:
    app: {{ template "elasticsearch.name" . | quote }}
    chart: {{ template "elasticsearch.chart" . | quote }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    role: "metrics"
  annotations:
{{ toYaml .Values.metrics.annotations | indent 4 }}
spec:
  ports:
  - name: metrics
    port: 9108
    targetPort: metrics
  selector:
    app: {{ template "elasticsearch.name" . | quote }}
    release: {{ .Release.Name | quote }}
    role: "metrics"
{{- end }}
